name: Symfony CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Setup PHP, with MySQL and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql
          tools: composer:v2

      - uses: actions/checkout@v3

      - name: Copy .env.test.example to .env.test
        run: cp .env.test.example .env.test

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Update .env.test with MySQL service credentials
        run: |
          echo "DATABASE_URL=mysql://root:root@127.0.0.1:3306/symfony_test" >> .env.test

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Prepare the Test Database
        run: php bin/console doctrine:database:create --env=test && php bin/console doctrine:schema:update --force --env=test

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit
